spring.application.name=RoleBasedBlog

# H2 DATABASE CONFIGURATION
spring.datasource.url=jdbc:h2:mem:blogdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=test
spring.datasource.password=test
spring.sql.init.platform=h2

# JPA & HIBERNATE SETTINGS
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 CONSOLE (Optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
